name: Hello World

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Open me
      run: |
        echo "Hello from GitHub Actions!"
        echo "I love you my darling, L&D 27 dic 2024"
        
    - name: Show Node.js version
      run: |
        node --version
        npm --version
        
    - name: List files
      run: |
        echo "Project structure:"
        ls -la 